import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../components/header';
import Footer from '@/components/footer';
import Announcement from '../components/anouncement';
import { Locomotive } from './locomotive';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BeniOuarain | Beni Ouarain Rugs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Announcement />
        <Locomotive>
          <Header />
          <div className='container mx-auto'>{children}</div>
          <Footer />
        </Locomotive>
      </body>
    </html>
  );
}
